// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package toml

import (
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/coveo/gotemplate/v3/errors"
	"github.com/stretchr/testify/assert"
)

var strFixture = tomlList(tomlListHelper.NewStringList(strings.Split("Hello World, I'm Foo Bar!", " ")...).AsArray())

func Test_list_Append(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		l      tomlIList
		values []interface{}
		want   tomlIList
	}{
		{"Empty", tomlList{}, []interface{}{1, 2, 3}, tomlList{1, 2, 3}},
		{"List of int", tomlList{1, 2, 3}, []interface{}{4, 5}, tomlList{1, 2, 3, 4, 5}},
		{"List of string", strFixture, []interface{}{"That's all folks!"}, tomlList{"Hello", "World,", "I'm", "Foo", "Bar!", "That's all folks!"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Append(tt.values...))
		})
	}
}

func Test_list_Prepend(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		l      tomlIList
		values []interface{}
		want   tomlIList
	}{
		{"Empty", tomlList{}, []interface{}{1, 2, 3}, tomlList{1, 2, 3}},
		{"List of int", tomlList{1, 2, 3}, []interface{}{4, 5}, tomlList{4, 5, 1, 2, 3}},
		{"List of string", strFixture, []interface{}{"That's all folks!"}, tomlList{"That's all folks!", "Hello", "World,", "I'm", "Foo", "Bar!"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Prepend(tt.values...))
		})
	}
}

func Test_list_AsArray(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		want []interface{}
	}{
		{"Empty List", tomlList{}, []interface{}{}},
		{"List of int", tomlList{1, 2, 3}, []interface{}{1, 2, 3}},
		{"List of string", strFixture, []interface{}{"Hello", "World,", "I'm", "Foo", "Bar!"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.AsArray())
		})
	}
}

func Test_TomlList_Strings(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		want []string
	}{
		{"Empty List", tomlList{}, []string{}},
		{"List of int", tomlList{1, 2, 3}, []string{"1", "2", "3"}},
		{"List of string", strFixture, []string{"Hello", "World,", "I'm", "Foo", "Bar!"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Strings())
		})
	}
}

func Test_list_Capacity(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlIList
		want int
	}{
		{"Empty List with 100 spaces", tomlListHelper.CreateList(0, 100), 100},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Capacity())
			assert.Equal(t, tt.l.Cap(), tt.l.Capacity(), "Cap and Capacity return different values")
		})
	}
}

func Test_list_Clone(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		want tomlIList
	}{
		{"Empty List", tomlList{}, tomlList{}},
		{"List of int", tomlList{1, 2, 3}, tomlList{1, 2, 3}},
		{"List of string", strFixture, tomlList{"Hello", "World,", "I'm", "Foo", "Bar!"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Clone())
		})
	}
}

func Test_list_Get(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		l       tomlList
		indexes []int
		want    interface{}
	}{
		{"Empty List", tomlList{}, []int{0}, nil},
		{"Negative index", tomlList{}, []int{-1}, nil},
		{"List of int", tomlList{1, 2, 3}, []int{0}, 1},
		{"List of string", strFixture, []int{1}, "World,"},
		{"Get last", strFixture, []int{-1}, "Bar!"},
		{"Get before last", strFixture, []int{-2}, "Foo"},
		{"A way to before last", strFixture, []int{-12}, nil},
		{"Get nothing", strFixture, nil, nil},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Get(tt.indexes...))
		})
	}
}

func Test_list_Len(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		want int
	}{
		{"Empty List", tomlList{}, 0},
		{"List of int", tomlList{1, 2, 3}, 3},
		{"List of string", strFixture, 5},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Len())
			assert.Equal(t, tt.l.Len(), tt.l.Count(), "Len and Count return different values")
		})
	}
}

func Test_CreateList(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		args    []int
		want    tomlIList
		wantErr error
	}{
		{"Empty", nil, tomlList{}, nil},
		{"With nil elements", []int{10}, make(tomlList, 10), nil},
		{"With capacity", []int{0, 10}, make(tomlList, 0, 10), nil},
		{"Too much args", []int{0, 10, 1}, nil, fmt.Errorf("CreateList only accept 2 arguments, size and capacity")},
	}
	for _, tt := range tests {
		var err error
		t.Run(tt.name, func(t *testing.T) {
			defer func() { err = errors.Trap(err, recover()) }()
			got := tomlListHelper.CreateList(tt.args...)
			assert.Equal(t, tt.want, got)
			assert.Equal(t, tt.want.Cap(), got.Capacity())
		})
		if tt.wantErr == nil {
			assert.NoError(t, err)
		} else {
			assert.EqualError(t, err, tt.wantErr.Error())
		}
	}
}

func Test_list_Create(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		args []int
		want tomlIList
	}{
		{"Empty", nil, nil, tomlList{}},
		{"Existing List", tomlList{1, 2}, nil, tomlList{}},
		{"With Empty spaces", tomlList{1, 2}, []int{5}, tomlList{nil, nil, nil, nil, nil}},
		{"With Capacity", tomlList{1, 2}, []int{0, 5}, tomlListHelper.CreateList(0, 5)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.l.Create(tt.args...)
			assert.Equal(t, tt.want, got)
			assert.Equal(t, tt.want.Cap(), got.Capacity())
		})
	}
}

func Test_list_New(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		args []interface{}
		want tomlIList
	}{
		{"Empty", nil, nil, tomlList{}},
		{"Existing List", tomlList{1, 2}, nil, tomlList{}},
		{"With elements", tomlList{1, 2}, []interface{}{3, 4, 5}, tomlList{3, 4, 5}},
		{"With strings", tomlList{1, 2}, []interface{}{"Hello", "World"}, tomlList{"Hello", "World"}},
		{"With nothing", tomlList{1, 2}, []interface{}{}, tomlList{}},
		{"With nil", tomlList{1, 2}, nil, tomlList{}},
		{"Adding array", tomlList{1, 2}, []interface{}{tomlList{3, 4}}, tomlList{3, 4}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.New(tt.args...))
		})
	}
}

func Test_list_CreateDict(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		l       tomlList
		args    []int
		want    tomlIDict
		wantErr error
	}{
		{"Empty", nil, nil, tomlDict{}, nil},
		{"With capacity", nil, []int{10}, tomlDict{}, nil},
		{"With too much parameter", nil, []int{10, 1}, nil, fmt.Errorf("CreateList only accept 1 argument for size")},
	}
	for _, tt := range tests {
		var err error
		t.Run(tt.name, func(t *testing.T) {
			defer func() { err = errors.Trap(err, recover()) }()
			assert.Equal(t, tt.want, tt.l.CreateDict(tt.args...))
		})
		if tt.wantErr == nil {
			assert.NoError(t, err)
		} else {
			assert.EqualError(t, err, tt.wantErr.Error())
		}
	}
}

func Test_list_Contains(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		args []interface{}
		want bool
	}{
		{"Empty List", nil, []interface{}{}, false},
		{"Search nothing", tomlList{1}, nil, true},
		{"Search nothing 2", tomlList{1}, []interface{}{}, true},
		{"Not there", tomlList{1}, []interface{}{2}, false},
		{"Included", tomlList{1, 2}, []interface{}{2}, true},
		{"Partially there", tomlList{1, 2}, []interface{}{2, 3}, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Contains(tt.args...))
			assert.Equal(t, tt.want, tt.l.Has(tt.args...))
		})
	}
}

func Test_list_First_Last(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		l         tomlList
		wantFirst interface{}
		wantLast  interface{}
	}{
		{"Nil", nil, nil, nil},
		{"Empty", tomlList{}, nil, nil},
		{"One element", tomlList{1}, 1, 1},
		{"Many element ", tomlList{1, "two", 3.1415, "four"}, 1, "four"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.wantFirst, tt.l.First())
			assert.Equal(t, tt.wantLast, tt.l.Last())
		})
	}
}

func Test_list_Pop(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		l        tomlList
		args     []int
		want     interface{}
		wantList tomlList
	}{
		{"Nil", nil, nil, nil, tomlList{}},
		{"Empty", tomlList{}, nil, nil, tomlList{}},
		{"Non existent", tomlList{}, []int{1}, nil, tomlList{}},
		{"Empty with args", tomlList{}, []int{1, 3}, tomlList{nil, nil}, tomlList{}},
		{"List with bad index", tomlList{0, 1, 2, 3, 4, 5}, []int{1, 3, 8}, tomlList{1, 3, nil}, tomlList{0, 2, 4, 5}},
		{"Pop last element", tomlList{0, 1, 2, 3, 4, 5}, nil, 5, tomlList{0, 1, 2, 3, 4}},
		{"Pop before last", tomlList{0, 1, 2, 3, 4, 5}, []int{-2}, 4, tomlList{0, 1, 2, 3, 5}},
		{"Pop first element", tomlList{0, 1, 2, 3, 4, 5}, []int{0}, 0, tomlList{1, 2, 3, 4, 5}},
		{"Pop all", tomlList{0, 1, 2, 3}, []int{0, 1, 2, 3}, tomlList{0, 1, 2, 3}, tomlList{}},
		{"Pop same element many time", tomlList{0, 1, 2, 3}, []int{1, 1, 2, 2}, tomlList{1, 1, 2, 2}, tomlList{0, 3}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, gotL := tt.l.Pop(tt.args...)
			assert.Equal(t, tt.want, got)
			assert.Equal(t, tt.wantList, gotL)
		})
	}
}

func Test_list_Intersect(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		args []interface{}
		want tomlList
	}{
		{"Empty List", nil, []interface{}{}, tomlList{}},
		{"Intersect nothing", tomlList{1}, nil, tomlList{}},
		{"Intersect nothing 2", tomlList{1}, []interface{}{}, tomlList{}},
		{"Not there", tomlList{1}, []interface{}{2}, tomlList{}},
		{"Included", tomlList{1, 2}, []interface{}{2}, tomlList{2}},
		{"Partially there", tomlList{1, 2}, []interface{}{2, 3}, tomlList{2}},
		{"With duplicates", tomlList{1, 2, 3, 4, 5, 4, 3, 2, 1}, []interface{}{3, 4, 5, 6, 7, 8, 7, 6, 5, 5, 4, 3}, tomlList{3, 4, 5}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Intersect(tt.args...))
		})
	}
}

func Test_list_Union(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		args []interface{}
		want tomlList
	}{
		{"Empty List", nil, []interface{}{}, tomlList{}},
		{"Intersect nothing", tomlList{1}, nil, tomlList{1}},
		{"Intersect nothing 2", tomlList{1}, []interface{}{}, tomlList{1}},
		{"Not there", tomlList{1}, []interface{}{2}, tomlList{1, 2}},
		{"Included", tomlList{1, 2}, []interface{}{2}, tomlList{1, 2}},
		{"Partially there", tomlList{1, 2}, []interface{}{2, 3}, tomlList{1, 2, 3}},
		{"With duplicates", tomlList{1, 2, 3, 4, 5, 4, 3, 2, 1}, []interface{}{8, 7, 6, 5, 6, 7, 8}, tomlList{1, 2, 3, 4, 5, 8, 7, 6}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Union(tt.args...))
		})
	}
}

func Test_list_Without(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		args []interface{}
		want tomlList
	}{
		{"Empty List", nil, []interface{}{}, tomlList{}},
		{"Remove nothing", tomlList{1}, nil, tomlList{1}},
		{"Remove nothing 2", tomlList{1}, []interface{}{}, tomlList{1}},
		{"Not there", tomlList{1}, []interface{}{2}, tomlList{1}},
		{"Included", tomlList{1, 2}, []interface{}{2}, tomlList{1}},
		{"Partially there", tomlList{1, 2}, []interface{}{2, 3}, tomlList{1}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Without(tt.args...))
		})
	}
}

func Test_list_Unique(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		want tomlList
	}{
		{"Empty List", nil, tomlList{}},
		{"Remove nothing", tomlList{1}, tomlList{1}},
		{"Duplicates following", tomlList{1, 1, 2, 3}, tomlList{1, 2, 3}},
		{"Duplicates not following", tomlList{1, 2, 3, 1, 2, 3, 4}, tomlList{1, 2, 3, 4}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Unique())
		})
	}
}

func Test_list_Reverse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		l    tomlList
		want tomlIList
	}{
		{"Empty List", tomlList{}, tomlList{}},
		{"List of int", tomlList{1, 2, 3}, tomlList{3, 2, 1}},
		{"List of string", strFixture, tomlList{"Bar!", "Foo", "I'm", "World,", "Hello"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Clone().Reverse())
		})
	}
}

func Test_list_Set(t *testing.T) {
	t.Parallel()

	type args struct {
		i int
		v interface{}
	}
	tests := []struct {
		name    string
		l       tomlIList
		args    args
		want    tomlIList
		wantErr error
	}{
		{"Empty", tomlList{}, args{2, 1}, tomlList{nil, nil, 1}, nil},
		{"List of int", tomlList{1, 2, 3}, args{0, 10}, tomlList{10, 2, 3}, nil},
		{"List of string", strFixture, args{2, "You're"}, tomlList{"Hello", "World,", "You're", "Foo", "Bar!"}, nil},
		{"Negative", tomlList{}, args{-1, "negative value"}, nil, fmt.Errorf("index must be positive number")},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.l.Clone().Set(tt.args.i, tt.args.v)
			assert.Equal(t, tt.want, got)
			if tt.wantErr == nil {
				assert.NoError(t, err)
			} else {
				assert.EqualError(t, err, tt.wantErr.Error())
			}
		})
	}
}

var mapFixture = map[string]interface{}{
	"int":     123,
	"float":   1.23,
	"string":  "Foo bar",
	"list":    []interface{}{1, "two"},
	"listInt": []int{1, 2, 3},
	"map": map[string]interface{}{
		"sub1": 1,
		"sub2": "two",
	},
	"mapInt": map[int]interface{}{
		1: 1,
		2: "two",
	},
}

var dictFixture = tomlDict(tomlDictHelper.AsDictionary(mapFixture).AsMap())

func dumpKeys(t *testing.T, d1, d2 tomlIDict) {
	for key := range d1.AsMap() {
		v1, v2 := d1.Get(key), d2.Get(key)
		if reflect.DeepEqual(v1, v2) {
			continue
		}
		t.Logf("'%[1]v' = %[2]v (%[2]T) vs %[3]v (%[3]T)", key, v1, v2)
	}
}

func Test_dict_AsMap(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		want map[string]interface{}
	}{
		{"Nil", nil, nil},
		{"Empty", tomlDict{}, map[string]interface{}{}},
		{"Map", dictFixture, map[string]interface{}(dictFixture)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.AsMap())
		})
	}
}

func Test_dict_Clone(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		keys []interface{}
		want tomlIDict
	}{
		{"Nil", nil, nil, tomlDict{}},
		{"Empty", tomlDict{}, nil, tomlDict{}},
		{"Map", dictFixture, nil, dictFixture},
		{"Map with Fields", dictFixture, []interface{}{"int", "list"}, tomlDict(dictFixture).Omit("float", "string", "listInt", "map", "mapInt")},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.d.Clone(tt.keys...)
			assert.Equal(t, tt.want, got)

			// Ensure that the copy is distinct from the original
			got.Set("NewField", "Test")
			assert.NotEqual(t, tt.want, got)
			assert.True(t, got.Has("NewField"))
			assert.Equal(t, "Test", got.Get("NewField"))
			assert.Equal(t, tt.want.Count()+1, got.Len())
			assert.False(t, tt.d.Has("NewField"), "Has: Original dictionary has been modified")
			assert.Nil(t, tt.d.Get("NewField"), "Get: Original dictionary has been modified")
		})
	}
}

func Test_TomlDict_CreateList(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		d            tomlDict
		args         []int
		want         tomlIList
		wantLen      int
		wantCapacity int
	}{
		{"Nil", nil, nil, tomlList{}, 0, 0},
		{"Empty", tomlDict{}, nil, tomlList{}, 0, 0},
		{"Map", dictFixture, nil, tomlList{}, 0, 0},
		{"Map with size", dictFixture, []int{3}, tomlList{nil, nil, nil}, 3, 3},
		{"Map with capacity", dictFixture, []int{0, 10}, tomlList{}, 0, 10},
		{"Map with size&capacity", dictFixture, []int{3, 10}, tomlList{nil, nil, nil}, 3, 10},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.d.CreateList(tt.args...)
			assert.Equal(t, tt.want, got)
			assert.Equal(t, tt.wantLen, got.Len())
			assert.Equal(t, tt.wantCapacity, got.Cap())
		})
	}
}

func Test_dict_Create(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		d       tomlDict
		args    []int
		want    tomlIDict
		wantErr error
	}{
		{"Empty", nil, nil, tomlDict{}, nil},
		{"With capacity", nil, []int{10}, tomlDict{}, nil},
		{"With too much parameter", nil, []int{10, 1}, nil, fmt.Errorf("CreateList only accept 1 argument for size")},
	}
	for _, tt := range tests {
		var err error
		t.Run(tt.name, func(t *testing.T) {
			defer func() { err = errors.Trap(err, recover()) }()
			assert.Equal(t, tt.want, tt.d.Create(tt.args...))
		})
		if tt.wantErr == nil {
			assert.NoError(t, err)
		} else {
			assert.EqualError(t, err, tt.wantErr.Error())
		}
	}
}

func Test_dict_Default(t *testing.T) {
	t.Parallel()

	type args struct {
		key    interface{}
		defVal interface{}
	}
	tests := []struct {
		name string
		d    tomlDict
		args args
		want interface{}
	}{
		{"Empty", nil, args{"Foo", "Bar"}, "Bar"},
		{"Map int", dictFixture, args{"int", 1}, 123},
		{"Map float", dictFixture, args{"float", 1}, 1.23},
		{"Map Non existant", dictFixture, args{"Foo", "Bar"}, "Bar"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.Default(tt.args.key, tt.args.defVal))
		})
	}
}

func Test_dict_Delete(t *testing.T) {
	t.Parallel()

	type args struct {
		key  interface{}
		keys []interface{}
	}
	tests := []struct {
		name    string
		d       tomlDict
		args    args
		want    tomlIDict
		wantErr error
	}{
		{"Empty", nil, args{}, tomlDict{}, fmt.Errorf("key <nil> not found")},
		{"Map", dictFixture, args{}, dictFixture, fmt.Errorf("key <nil> not found")},
		{"Non existant key", dictFixture, args{"Test", nil}, dictFixture, fmt.Errorf("key Test not found")},
		{"Map with keys", dictFixture, args{"int", []interface{}{"list"}}, dictFixture.Clone("float", "string", "listInt", "map", "mapInt"), nil},
		{"Map with keys + non existant", dictFixture, args{"int", []interface{}{"list", "Test"}}, dictFixture.Clone("float", "string", "listInt", "map", "mapInt"), fmt.Errorf("key Test not found")},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.d.Clone().Delete(tt.args.key, tt.args.keys...)
			assert.Equal(t, tt.want, got)
			if tt.wantErr == nil {
				assert.NoError(t, err)
			} else {
				assert.EqualError(t, err, tt.wantErr.Error())
			}
		})
	}
}

func Test_dict_Flush(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		keys []interface{}
		want tomlIDict
	}{
		{"Empty", nil, nil, tomlDict{}},
		{"Map", dictFixture, nil, tomlDict{}},
		{"Non existant key", dictFixture, []interface{}{"Test"}, dictFixture},
		{"Map with keys", dictFixture, []interface{}{"int", "list"}, dictFixture.Clone("float", "string", "listInt", "map", "mapInt")},
		{"Map with keys + non existant", dictFixture, []interface{}{"int", "list", "Test"}, dictFixture.Clone("float", "string", "listInt", "map", "mapInt")},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			d := tt.d.Clone()
			got := d.Flush(tt.keys...)
			assert.Equal(t, tt.want, got)
			assert.Equal(t, d, got)
		})
	}
}

func Test_dict_Keys(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		want tomlIList
	}{
		{"Empty", nil, tomlList{}},
		{"Map", dictFixture, tomlList{str("float"), str("int"), str("list"), str("listInt"), str("map"), str("mapInt"), str("string")}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.GetKeys())
		})
	}
}

func Test_dict_KeysAsString(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		want strArray
	}{
		{"Empty", nil, strArray{}},
		{"Map", dictFixture, strArray{"float", "int", "list", "listInt", "map", "mapInt", "string"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.KeysAsString())
		})
	}
}

func Test_dict_Merge(t *testing.T) {
	t.Parallel()

	adding1 := tomlDict{
		"int":        1000,
		"Add1Int":    1,
		"Add1String": "string",
	}
	adding2 := tomlDict{
		"Add2Int":    1,
		"Add2String": "string",
		"map": map[string]interface{}{
			"sub1":   2,
			"newVal": "NewValue",
		},
	}
	type args struct {
		tomlDict tomlIDict
		dicts    []tomlIDict
	}
	tests := []struct {
		name string
		d    tomlDict
		args args
		want tomlIDict
	}{
		{"Empty", nil, args{nil, []tomlIDict{}}, tomlDict{}},
		{"Add map to empty", nil, args{dictFixture, []tomlIDict{}}, dictFixture},
		{"Add map to same map", dictFixture, args{dictFixture, []tomlIDict{}}, dictFixture},
		{"Add empty to map", dictFixture, args{nil, []tomlIDict{}}, dictFixture},
		{"Add new1 to map", dictFixture, args{adding1, []tomlIDict{}}, dictFixture.Clone().Merge(adding1)},
		{"Add new2 to map", dictFixture, args{adding2, []tomlIDict{}}, dictFixture.Clone().Merge(adding2)},
		{"Add new1 & new2 to map", dictFixture, args{adding1, []tomlIDict{adding2}}, dictFixture.Clone().Merge(adding1, adding2)},
		{"Add new1 & new2 to map", dictFixture, args{adding1, []tomlIDict{adding2}}, dictFixture.Clone().Merge(adding1).Merge(adding2)},
	}
	for _, tt := range tests {
		go t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.Clone().Merge(tt.args.tomlDict, tt.args.dicts...))
		})
	}
}

func Test_dict_Values(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		want tomlIList
	}{
		{"Empty", nil, tomlList{}},
		{"Map", dictFixture, tomlList{1.23, 123, tomlList{1, "two"}, tomlList{1, 2, 3}, tomlDict{"sub1": 1, "sub2": "two"}, tomlDict{"1": 1, "2": "two"}, "Foo bar"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.GetValues())
		})
	}
}

func Test_dict_Pop(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		d          tomlDict
		args       []interface{}
		want       interface{}
		wantObject tomlIDict
	}{
		{"Nil", dictFixture, nil, nil, dictFixture},
		{"Pop one element", dictFixture, []interface{}{"float"}, 1.23, dictFixture.Omit("float")},
		{"Pop missing element", dictFixture, []interface{}{"undefined"}, nil, dictFixture},
		{"Pop element twice", dictFixture, []interface{}{"int", "int", "string"}, tomlList{123, 123, "Foo bar"}, dictFixture.Omit("int", "string")},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			d := tt.d.Clone()
			assert.Equal(t, tt.want, d.Pop(tt.args...))
			assert.Equal(t, tt.wantObject, d)
		})
	}
}

func Test_dict_Add(t *testing.T) {
	t.Parallel()

	type args struct {
		key interface{}
		v   interface{}
	}
	tests := []struct {
		name string
		d    tomlDict
		args args
		want tomlIDict
	}{
		{"Empty", nil, args{"A", 1}, tomlDict{"A": 1}},
		{"With element", tomlDict{"A": 1}, args{"A", 2}, tomlDict{"A": tomlList{1, 2}}},
		{"With element, another value", tomlDict{"A": 1}, args{"B", 2}, tomlDict{"A": 1, "B": 2}},
		{"With list element", tomlDict{"A": tomlList{1, 2}}, args{"A", 3}, tomlDict{"A": tomlList{1, 2, 3}}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.Add(tt.args.key, tt.args.v))
		})
	}
}

func Test_dict_Set(t *testing.T) {
	t.Parallel()

	type args struct {
		key interface{}
		v   interface{}
	}
	tests := []struct {
		name string
		d    tomlDict
		args args
		want tomlIDict
	}{
		{"Empty", nil, args{"A", 1}, tomlDict{"A": 1}},
		{"With element", tomlDict{"A": 1}, args{"A", 2}, tomlDict{"A": 2}},
		{"With element, another value", tomlDict{"A": 1}, args{"B", 2}, tomlDict{"A": 1, "B": 2}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.Set(tt.args.key, tt.args.v))
		})
	}
}

func Test_dict_Transpose(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		d    tomlDict
		want tomlIDict
	}{
		{"Empty", nil, tomlDict{}},
		{"Base", tomlDict{"A": 1}, tomlDict{"1": str("A")}},
		{"Multiple", tomlDict{"A": 1, "B": 2, "C": 1}, tomlDict{"1": tomlList{str("A"), str("C")}, "2": str("B")}},
		{"List", tomlDict{"A": []int{1, 2, 3}, "B": 2, "C": 3}, tomlDict{"1": str("A"), "2": tomlList{str("A"), str("B")}, "3": tomlList{str("A"), str("C")}}},
		{"Complex", tomlDict{"A": tomlDict{"1": 1, "2": 2}, "B": 2, "C": 3}, tomlDict{"2": str("B"), "3": str("C"), fmt.Sprint(tomlDict{"1": 1, "2": 2}): str("A")}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.d.Transpose())
		})
	}
}

func Test_TomlList_Get(t *testing.T) {
	type args struct {
		indexes []int
	}
	tests := []struct {
		name string
		l    tomlList
		args args
		want interface{}
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.Get(tt.args.indexes...))
		})
	}
}

func Test_TomlList_TypeName(t *testing.T) {
	tests := []struct {
		name string
		l    tomlList
		want str
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.l.TypeName())
		})
	}
}

func Test_Toml_TypeName(t *testing.T) {
	t.Run("list", func(t *testing.T) { assert.Equal(t, tomlList{}.TypeName(), str("Toml")) })
	t.Run("dict", func(t *testing.T) { assert.Equal(t, tomlDict{}.TypeName(), str("Toml")) })
}

func Test_Toml_GetHelper(t *testing.T) {
	t.Run("list", func(t *testing.T) {
		gotD, gotL := tomlList{}.GetHelpers()
		assert.Equal(t, gotD.CreateDictionary().TypeName(), tomlDictHelper.CreateDictionary().TypeName())
		assert.Equal(t, gotL.CreateList().TypeName(), tomlListHelper.CreateList().TypeName())
	})
	t.Run("dict", func(t *testing.T) {
		gotD, gotL := tomlDict{}.GetHelpers()
		assert.Equal(t, gotD.CreateDictionary().TypeName(), tomlDictHelper.CreateDictionary().TypeName())
		assert.Equal(t, gotL.CreateList().TypeName(), tomlListHelper.CreateList().TypeName())
	})
}
